#!/usr/bin/env bash
echo "==delete bucket"
if [ -z "$1" ]; then
  echo "❌ No argument provided. Please pass the bucket name as the first argument."
  exit 1
fi

BUCKET_NAME=$1

aws s3api delete-bucket \
--bucket $BUCKET_NAME \
