#!/usr/bin/env bash
echo = "== delete-object"

if [ -z "$1" ]; then
  echo "❌ No argument provided. Please pass the bucket name as the first argument."
  exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete_objects.json